#theme: jekyll-theme-minimal
remote_theme: pages-themes/modernist@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Venkat Kollimarla
description: A collection of technical blogs and talks on machine learning and data science.
show_downloads: false
google_analytics: G-CZY5J456Q2
logo: ./venkat.jpg
