theme: jekyll-theme-minimal
title: Venkat Kollimarla
description: A collection of technical blogs and talks on machine learning and data science.
show_downloads: false
google_analytics: G-CZY5J456Q2
logo: ./venkat.jpg
